### ISSUE TITLE
Artifactory home is not organized well

### ISSUE THREAD

**Issue by sonnysideup** [JFrogDev/artifactory-docker-builder#11]
I just attempted to map a single named volume (`/var/opt/jfrog/artifactory`) into my Artifactory container only to discover that this setup renders the container useless. A single, root-level volume masks critical subdirs that contain tomcat, your webapp and other configuration files. The online docs indicate that the user needs to map 3 separate volumes for **data**, **etc** and **logs** inside the homedir, but why not just provide an option to map the entire homedir?

There are possibly *decent reasons* why someone might want to map several volumes here, but the only valid use case that I can think of right now is a disk I/O requirement for the data directory.

This requirement feels like a workaround for bad design decision to co-locate static and variable assets in the same base directory, and it it makes it a chore to work with persistent volumes in both Mesos and K8s; I don't want to create 6 new volume objects just to store artifactory data.

**Comment by eldada** [comment]
You are right. The current Docker image requires a lot of setup and hardens the integration with container orchestration tools.
I'm happy to tell you that a new major release of Artifactory is coming soon, which has a redesigned Docker image that one of its changes is the need for a single volume mount for `/var/opt/jfrog/artifactory` as you would expect.
We will also share some example configurations for docker-compose, K8s, DC/OS and will welcome more contributions.
I will close this after the new release.

**Comment by sonnysideup** [comment]
@eldada I'm curious, without any promises of course, I wonder if you have a _very tentative_ timeline for that release?

**Comment by eldada** [comment]
The time frame is days. I hope for good news soon 😄

**Comment by eldada** [comment]
@drywheat - I'm happy to let you know that the new Artifactory 5 in released!
You can get details on Docker in the official Wiki: https://www.jfrog.com/confluence/display/RTF/Running+with+Docker
We also setup a new repository with Docker examples: https://github.com/JFrogDev/artifactory-docker-examples. This currently has only Docker compose examples, but will extend to other deployments in the future.

I hope this will meet your needs. Any feedback is always welcome! I'm closing this issue.

**Comment by sonnysideup** [comment]
Thanks @eldada, I'll start checking it out.
