### ISSUE TITLE
jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss no longer starts

### ISSUE THREAD

**Issue by jamshid** [JFrogDev/artifactory-docker-builder#4]
Sorry if this isn't the right forum, but I'm no longer able to run artifactory in docker. It has been running fine for last half of 2015 so I wonder if a recent image, java, or docker change has introduced the problem.

I'm seeing it in a new digitalocean docker server so it should be easy to reproduce.

```
$ docker run --name art1 -p 8081:8081  jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss
nginx: unrecognized service
/usr/bin/java
Starting Artifactory tomcat as user artifactory...
Max number of open files: 524288
Using ARTIFACTORY_HOME: /var/opt/jfrog/artifactory
Using ARTIFACTORY_PID: /var/opt/jfrog/run/artifactory.pid
Creating directory /var/opt/jfrog/artifactory/logs/catalina
Creating directory /var/opt/jfrog/artifactory/temp
Creating directory /var/opt/jfrog/artifactory/work
Tomcat started.

** ERROR: Artifactory Tomcat server did not start in 60 seconds. Please check the logs
```

The container stops. Nothing seems wrong in /var/opt/jfrog/artifactory/logs.
[artlogs.zip](https://github.com/JFrogDev/artifactory-docker-builder/files/80180/artlogs.zip)

catalina/catalina.out:

```
   sun.boot.library.path                                                 | /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-0.b17.el6_7.x86_64/jre/lib/amd64
...
2016-01-06 18:03:14,575 [art-init] [INFO ] (o.a.s.ArtifactoryApplicationContext:406) - Artifactory application context is ready.
2016-01-06 18:03:14,578 [art-init] [INFO ] (o.a.w.s.ArtifactoryContextConfigListener:219) - 
###########################################################
### Artifactory successfully started (10.290 seconds)   ###
###########################################################
```

artifactory.log:

```
 Version:  4.4.0                                   __/ |
 Revision: 40080                                  |___/
...
2016-01-06 18:03:14,575 [art-init] [INFO ] (o.a.s.ArtifactoryApplicationContext:406) - Artifactory application context is ready.
2016-01-06 18:03:14,578 [art-init] [INFO ] (o.a.w.s.ArtifactoryContextConfigListener:219) - 
###########################################################
### Artifactory successfully started (10.290 seconds)   ###
###########################################################
```

PS: I used to use jfrog-docker-registry.bintray.io/artifactory/artifactory-oss but instructions at https://www.jfrog.com/confluence/display/RTF/Running+with+Docker recently changed?

Is there an older working version I can revert to? I don't know how to list the available image tags.

Thanks, let me know if you need any other information or want me to run a test.

**Comment by jamshid** [comment]
`jstack <java pid>` finally worked _once_ -- normally reports

```
82: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding

and 

# jstack -F 82
Attaching to process ID 82, please wait...
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
    at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
```

Anyway I saw the below thread, and searching on it shows that it can be a problem, causing slow / hanging tomcat startup. 

```
"localhost-startStop-1" #16 daemon prio=5 os_prio=0 tid=0x00007fa90c002000 nid=0x81 runnable [0x00007fa9485e5000]
   java.lang.Thread.State: RUNNABLE
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:255)
    at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:539)
    at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
    at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:203)
    at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:221)
    - locked <0x00000000805a5740> (a sun.security.provider.SecureRandom)
    at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
    - locked <0x00000000805a57a0> (a java.security.SecureRandom)
    at java.security.SecureRandom.next(SecureRandom.java:491)
```

So I tried the suggested workaround `-e RUNTIME_OPTS="-Djava.security.egd=file:/dev/./urandom"`. Fingers crossed that this is a consistent fix!

**Comment by matankatz** [comment]
Hi jamshid,

Thank you for your feedback.
As you mentioned Tomcat server start took longer than 60 seconds.
We have added "START_TMO" env variable to extend the init timeout of tomcat.
This timeout by default is 60 seconds.

You can extend the timeout as another protection for the container startup process.

**Comment by jamshid** [comment]
Okay, thanks, found your https://www.jfrog.com/jira/browse/RTFACT-7842. Feel free to close this.

Minor issue: the error messages in /etc/init.d/artifactory are still hardcoded, they don't show the env variable values.

I still saw timeouts even at 120 seconds. Didn't test longer, since that also causes problems for monitoring tools and scripts. If SecureRandom is the most common culprit, seems good to document or even default the RUNTIME_OPTS workaround.

PS: thanks for providing this artifactory container, it sure makes Dockerfiles that use maven much faster.

**Comment by matankatz** [comment]
Resolved in https://www.jfrog.com/jira/browse/RTFACT-7842

**Comment by jfexart** [comment]
@jamshid thank! I had the same problem and your workaround solved it.

@matankatz RUNTIME_OPTS fix it, but with START_TMO the problem persisted.
