### ISSUE TITLE
can we pass the license information in command line?

### ISSUE THREAD

**Issue by jamesgunja** [JFrogDev/artifactory-docker-builder#8]
can we pass the license information in command line?

**Comment by matankatz** [comment]
In order to start Artifactory with license on startup you can mount it during the startup of the container using -v option.
docker run -d -v [path to license]:/etc/opt/jfrog/artifactory/artifactory.lic jfrog-docker-reg2.bintray.io/jfrog/artifactory-registry

**Comment by jamesgunja** [comment]
Thanks! It works!!
